<a href="https://colab.research.google.com/github/Meena-27/HunarIntern/blob/main/HunarIntern_Task_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***TASK 1***:
## **DATA CLEANING**

In [1]:
import numpy as np
import pandas as pd

Reading the data from the given dataset

In [2]:
df=pd.read_csv("/content/food_coded.csv")

Performing basic table functions

In [7]:
df.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

In [8]:
df.tail()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

In [9]:
len(df.index)

125

In [11]:
df.shape[1]

61

In [12]:
df.columns

Index(['GPA', 'Gender', 'breakfast', 'calories_chicken', 'calories_day',
       'calories_scone', 'coffee', 'comfort_food', 'comfort_food_reasons',
       'comfort_food_reasons_coded', 'cook', 'comfort_food_reasons_coded.1',
       'cuisine', 'diet_current', 'diet_current_coded', 'drink',
       'eating_changes', 'eating_changes_coded', 'eating_changes_coded1',
       'eating_out', 'employment', 'ethnic_food', 'exercise',
       'father_education', 'father_profession', 'fav_cuisine',
       'fav_cuisine_coded', 'fav_food', 'food_childhood', 'fries', 'fruit_day',
       'grade_level', 'greek_food', 'healthy_feeling', 'healthy_meal',
       'ideal_diet', 'ideal_diet_coded', 'income', 'indian_food',
       'italian_food', 'life_rewarding', 'marital_status',
       'meals_dinner_friend', 'mother_education', 'mother_profession',
       'nutritional_check', 'on_off_campus', 'parents_cook', 'pay_meal_out',
       'persian_food', 'self_perception_weight', 'soup', 'sports', 'thai_food',
       'tortilla_calories', 'turkey_calories', 'type_sports', 'veggies_day',
       'vitamins', 'waffle_calories', 'weight'],
      dtype='object')

In [13]:
df.index

RangeIndex(start=0, stop=125, step=1)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          123 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    object
dtypes: float64(20), int64(27), object(14)
memory usage: 59.7+ KB

In [15]:
df.describe()

,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,cuisine,...,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,veggies_day,vitamins,waffle_calories
count,125.000000,125.000000,125.000000,106.000000,124.000000,125.00000,106.000000,122.000000,125.000000,108.000000,...,124.000000,124.000000,124.000000,123.000000,125.000000,124.000000,125.000000,125.000000,125.000000,125.000000
mean,1.392000,1.112000,577.320000,3.028302,505.241935,1.75200,2.698113,2.786885,2.688000,1.388889,...,2.806452,3.120968,1.217742,1.390244,3.336000,947.580645,555.040000,4.008000,1.512000,1073.400000
std,0.490161,0.316636,131.214156,0.639308,230.840506,0.43359,1.972042,1.038351,1.910987,0.974759,...,1.423824,1.115980,0.414385,0.489800,1.436528,202.090179,152.370379,1.081337,0.501867,248.667092
min,1.000000,1.000000,265.000000,2.000000,315.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,580.000000,345.000000,1.000000,1.000000,575.000000
25%,1.000000,1.000000,430.000000,3.000000,420.000000,2.00000,2.000000,2.000000,2.000000,1.000000,...,2.000000,2.000000,1.000000,1.000000,2.000000,725.000000,500.000000,3.000000,1.000000,900.000000
50%,1.000000,1.000000,610.000000,3.000000,420.000000,2.00000,2.000000,3.000000,2.000000,1.000000,...,3.000000,3.000000,1.000000,1.000000,3.000000,940.000000,500.000000,4.000000,2.000000,900.000000
75%,2.000000,1.000000,720.000000,3.000000,420.000000,2.00000,3.000000,3.000000,3.000000,1.000000,...,4.000000,4.000000,1.000000,2.000000,5.000000,1165.000000,690.000000,5.000000,2.000000,1315.000000
max,2.000000,2.000000,720.000000,4.000000,980.000000,2.00000,9.000000,5.000000,9.000000,6.000000,...,5.000000,6.000000,2.000000,2.000000,5.000000,1165.000000,850.000000,5.000000,2.000000,1315.000000

In [16]:
df.isnull().sum()

GPA                  2
Gender               0
breakfast            0
calories_chicken     0
calories_day        19
                    ..
type_sports         26
veggies_day          0
vitamins             0
waffle_calories      0
weight               2
Length: 61, dtype: int64

**For GPA**:
 Since GPA is a numeric column, using the mean or median to fill missing values makes sense depending on its distribution.

In [20]:
print(df['GPA'].dtype)

object

In [21]:
df['GPA'] = pd.to_numeric(df['GPA'], errors='coerce')

In [22]:
# Recalculate the mean after conversion
mean_gpa = df['GPA'].mean()

# Fill missing values with the mean
df['GPA'].fillna(mean_gpa, inplace=True)

# Print the result
print(f"Filled missing values in GPA with Mean: {mean_gpa}")

Filled missing values in GPA with Mean: 3.4155583333333337

**For calories_day (Numeric Column):**
calories_day is also numeric, so we handle it similarly by deciding between mean or median.

In [23]:
df['calories_day'] = pd.to_numeric(df['calories_day'], errors='coerce')

In [24]:
mean_calories_day = df['calories_day'].mean()
df['calories_day'].fillna(mean_calories_day, inplace=True)

In [25]:
print(f"Filled missing values in calories_day with Mean: {mean_calories_day}")

Filled missing values in calories_day with Mean: 3.0283018867924527

**TYPE_SPORTS**:
it is a categorical value.so we cant calculate mean or median for the data.we calculate mode of the data.

In [26]:
df['type_sports'] = df['type_sports'].astype(str)
mode_type_sports = df['type_sports'].mode()[0]
df['type_sports'].fillna(mode_type_sports, inplace=True)
print(f"Filled missing values in type_sports with Mode: {mode_type_sports}")

Filled missing values in type_sports with Mode: nan

**WEIGHT**:
it is a numeric value.The choice between using the mean or median depends on the distribution of the data.If the data is not heavily skewed, the mean is used because it provides a central value.

In [27]:
df['weight'] = pd.to_numeric(df['weight'], errors='coerce')
fill_value = df['weight'].mean() if df['weight'].skew() < 1 else df['weight'].median()
df['weight'].fillna(fill_value, inplace=True)
print(f"Filled missing values in 'weight' with: {fill_value}")

Filled missing values in 'weight' with: 158.5

**Check for Remaining Missing Values**:
After filling in the missing values, it's good practice to check if there are still any missing values left in the dataset.

In [28]:
print("\nMissing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
GPA                 0
Gender              0
breakfast           0
calories_chicken    0
calories_day        0
                   ..
type_sports         0
veggies_day         0
vitamins            0
waffle_calories     0
weight              0
Length: 61, dtype: int64

**Removing Duplicate Rows**:
Now that we've handled missing values, we will check and remove any duplicate rows. This ensures that we have unique records.

In [30]:
initial_row_count = df.shape[0]

In [31]:
df.drop_duplicates(inplace=True)

In [32]:
new_row_count = df.shape[0]
print(f"\nRemoved {initial_row_count - new_row_count} duplicate rows.")

Removed 0 duplicate rows.

** Removing Duplicate Columns**:
Sometimes, datasets may have duplicate columns (i.e., two columns with the same data).

In [33]:
df = df.loc[:, ~df.columns.duplicated()]
print("\nColumns after removing duplicates:", df.columns.tolist())

Columns after removing duplicates: ['GPA', 'Gender', 'breakfast', 'calories_chicken', 'calories_day', 'calories_scone', 'coffee', 'comfort_food', 'comfort_food_reasons', 'comfort_food_reasons_coded', 'cook', 'comfort_food_reasons_coded.1', 'cuisine', 'diet_current', 'diet_current_coded', 'drink', 'eating_changes', 'eating_changes_coded', 'eating_changes_coded1', 'eating_out', 'employment', 'ethnic_food', 'exercise', 'father_education', 'father_profession', 'fav_cuisine', 'fav_cuisine_coded', 'fav_food', 'food_childhood', 'fries', 'fruit_day', 'grade_level', 'greek_food', 'healthy_feeling', 'healthy_meal', 'ideal_diet', 'ideal_diet_coded', 'income', 'indian_food', 'italian_food', 'life_rewarding', 'marital_status', 'meals_dinner_friend', 'mother_education', 'mother_profession', 'nutritional_check', 'on_off_campus', 'parents_cook', 'pay_meal_out', 'persian_food', 'self_perception_weight', 'soup', 'sports', 'thai_food', 'tortilla_calories', 'turkey_calories', 'type_sports', 'veggies_day', 'vitamins', 'waffle_calories', 'weight']